config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  resources :permitions
  resources :roles
  resources :games
  resources :categories
  resources :game_studios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/permition.rb
class Permition < ApplicationRecord
  belongs_to :role
end

app/controllers/permitions_controller.rb
class PermitionsController < ApplicationController
  before_action :set_permition, only: %i[ show edit update destroy ]

  # GET /permitions or /permitions.json
  def index
    @permitions = Permition.all
  end

  # GET /permitions/1 or /permitions/1.json
  def show
  end

  # GET /permitions/new
  def new
    @permition = Permition.new
  end

  # GET /permitions/1/edit
  def edit
  end

  # POST /permitions or /permitions.json
  def create
    @permition = Permition.new(permition_params)

    respond_to do |format|
      if @permition.save
        format.html { redirect_to permition_url(@permition), notice: "Permition was successfully created." }
        format.json { render :show, status: :created, location: @permition }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @permition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permitions/1 or /permitions/1.json
  def update
    respond_to do |format|
      if @permition.update(permition_params)
        format.html { redirect_to permition_url(@permition), notice: "Permition was successfully updated." }
        format.json { render :show, status: :ok, location: @permition }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @permition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permitions/1 or /permitions/1.json
  def destroy
    @permition.destroy

    respond_to do |format|
      format.html { redirect_to permitions_url, notice: "Permition was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permition
      @permition = Permition.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def permition_params
      params.require(:permition).permit(:role_id, :can_lock_user, :can_edit_role, :can_edit_game, :can_edit_categories)
    end
end

app/helpers/permitions_helper.rb
module PermitionsHelper
end

app/views/permitions/_form.html.erb
<%= form_with(model: permition) do |form| %>
  <% if permition.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(permition.errors.count, "error") %> prohibited this permition from being saved:</h2>

      <ul>
        <% permition.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :role_id, style: "display: block" %>
    <%= form.text_field :role_id %>
  </div>

  <div>
    <%= form.label :can_lock_user, style: "display: block" %>
    <%= form.check_box :can_lock_user %>
  </div>

  <div>
    <%= form.label :can_edit_role, style: "display: block" %>
    <%= form.check_box :can_edit_role %>
  </div>

  <div>
    <%= form.label :can_edit_game, style: "display: block" %>
    <%= form.check_box :can_edit_game %>
  </div>

  <div>
    <%= form.label :can_edit_categories, style: "display: block" %>
    <%= form.check_box :can_edit_categories %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/permitions/_permition.html.erb
<div id="<%= dom_id permition %>">
  <p>
    <strong>Role:</strong>
    <%= permition.role_id %>
  </p>

  <p>
    <strong>Can lock user:</strong>
    <%= permition.can_lock_user %>
  </p>

  <p>
    <strong>Can edit role:</strong>
    <%= permition.can_edit_role %>
  </p>

  <p>
    <strong>Can edit game:</strong>
    <%= permition.can_edit_game %>
  </p>

  <p>
    <strong>Can edit categories:</strong>
    <%= permition.can_edit_categories %>
  </p>

</div>

app/views/permitions/edit.html.erb
<h1>Editing permition</h1>

<%= render "form", permition: @permition %>

<br>

<div>
  <%= link_to "Show this permition", @permition %> |
  <%= link_to "Back to permitions", permitions_path %>
</div>

app/views/permitions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Permitions</h1>

<div id="permitions">
  <% @permitions.each do |permition| %>
    <%= render permition %>
    <p>
      <%= link_to "Show this permition", permition %>
    </p>
  <% end %>
</div>

<%= link_to "New permition", new_permition_path %>

app/views/permitions/new.html.erb
<h1>New permition</h1>

<%= render "form", permition: @permition %>

<br>

<div>
  <%= link_to "Back to permitions", permitions_path %>
</div>

app/views/permitions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @permition %>

<div>
  <%= link_to "Edit this permition", edit_permition_path(@permition) %> |
  <%= link_to "Back to permitions", permitions_path %>

  <%= button_to "Destroy this permition", @permition, method: :delete %>
</div>