config/routes.rb
Rails.application.routes.draw do
  mount_devise_token_auth_for 'User', at: 'auth'
  resources :permitions
  resources :roles
  resources :games
  resources :categories
  resources :game_studios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/game_studio.rb
class GameStudio < ApplicationRecord
  has_many :games
end

app/controllers/game_studios_controller.rb
class GameStudiosController < ApplicationController
  before_action :set_game_studio, only: %i[show edit update destroy]

  # GET /game_studios or /game_studios.json
  def index
    @game_studios = GameStudio.all
  end

  # GET /game_studios/1 or /game_studios/1.json
  def show; end

  # GET /game_studios/new
  def new
    @game_studio = GameStudio.new
  end

  # GET /game_studios/1/edit
  def edit; end

  # POST /game_studios or /game_studios.json
  def create
    @game_studio = GameStudio.new(game_studio_params)

    if @game_studio.save
      render :show, status: :created, location: @game_studio
    else
      render json: @game_studio.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /game_studios/1 or /game_studios/1.json
  def update
    if @game_studio.update(game_studio_params)
      render :show, status: :ok, location: @game_studio
    else
      render json: @game_studio.errors, status: :unprocessable_entity
    end
  end

  # DELETE /game_studios/1 or /game_studios/1.json
  def destroy
    @game_studio.destroy

    respond_to do |_format|
      head :no_content
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game_studio
    @game_studio = GameStudio.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_studio_params
    params.require(:game_studio).permit(:name)
  end
end

app/helpers/game_studios_helper.rb
module GameStudiosHelper
end

app/views/game_studios/_form.html.erb
<%= form_with(model: game_studio) do |form| %>
  <% if game_studio.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game_studio.errors.count, "error") %> prohibited this game_studio from being saved:</h2>

      <ul>
        <% game_studio.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/game_studios/_game_studio.html.erb
<div id="<%= dom_id game_studio %>">
  <p>
    <strong>Name:</strong>
    <%= game_studio.name %>
  </p>

</div>

app/views/game_studios/edit.html.erb
<h1>Editing game studio</h1>

<%= render "form", game_studio: @game_studio %>

<br>

<div>
  <%= link_to "Show this game studio", @game_studio %> |
  <%= link_to "Back to game studios", game_studios_path %>
</div>

app/views/game_studios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Game studios</h1>

<div id="game_studios">
  <% @game_studios.each do |game_studio| %>
    <%= render game_studio %>
    <p>
      <%= link_to "Show this game studio", game_studio %>
    </p>
  <% end %>
</div>

<%= link_to "New game studio", new_game_studio_path %>

app/views/game_studios/new.html.erb
<h1>New game studio</h1>

<%= render "form", game_studio: @game_studio %>

<br>

<div>
  <%= link_to "Back to game studios", game_studios_path %>
</div>

app/views/game_studios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game_studio %>

<div>
  <%= link_to "Edit this game studio", edit_game_studio_path(@game_studio) %> |
  <%= link_to "Back to game studios", game_studios_path %>

  <%= button_to "Destroy this game studio", @game_studio, method: :delete %>
</div>